version: '3.5'

networks:
  frontend-network:
    external: true
    name: "${FRONTEND_NETWORK_NAME}"

# Set general setting for services logging
x-logging-settings: &logging-settings
  logging:
    driver: "json-file"
    options:
      max-file: "2"
      max-size: "5m"

services:
  # NGINX container for PHP-FPM with Yii2 Administrative panel
  nginx-sem_soft:

    image: nginx
    <<: *logging-settings
    restart: always
    environment:

      VIRTUAL_HOST: "${VIRTUAL_HOST}"
      LETSENCRYPT_HOST: "${VIRTUAL_HOST}"
    volumes:
      - ./dist:/usr/share/nginx/html

    networks:
      - frontend-network